"""Add fuel_prices table

Revision ID: 42d7303d3ec7
Revises: dd2200be9940
Create Date: 2026-10-06 08:32:41.585592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d7303d3ec7'
down_revision: Union[str, Sequence[str], None] = 'dd2200be9940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('price_per_liter', sa.Integer(), nullable=False),
    sa.Column('parsed_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_prices_fuel_type'), 'fuel_prices', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_fuel_prices_id'), 'fuel_prices', ['id'], unique=False)
    op.create_index(op.f('ix_fuel_prices_parsed_at'), 'fuel_prices', ['parsed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_prices_parsed_at'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_id'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_fuel_type'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    # ### end Alembic commands ###
